version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.2
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Diskordia.Columbus.sln && dotnet publish ./Diskordia.Columbus.sln -c Release -o ./obj/Docker/publish"
