version: '3'

services:
  diskordia.columbus.backgroundworker:
    image: columbus.azurecr.io/diskordia.columbus.backgroundworker
    build:
      context: ./Diskordia.Columbus.BackgroundWorker
      dockerfile: Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  diskordia.columbus.faredealscanner:
    image: diskordia.columbus.faredealscanner
    build:
      context: ./Diskordia.Columbus.FareDealScanner
      dockerfile: Dockerfile
